CREATE TABLE IF NOT EXISTS ops_delivery_decision_config (
  id           TINYINT      NOT NULL,
  payload_json LONGTEXT     NOT NULL,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
