CREATE TABLE IF NOT EXISTS ops_renewal_settings (
  id         TINYINT      NOT NULL,
  payload_json LONGTEXT   NOT NULL,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
