CREATE TABLE IF NOT EXISTS ops_suppliers (
  supplier_id VARCHAR(64) PRIMARY KEY,
  payload_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
